import os
import os.path as osp
import sys

class Config:
    # vis setting
    visualization = dict(
        enable=False,                 # 推理时是否保存ViT中间层可视化
        save_dir='./vit_vis', # 保存目录
        layers=[2, 5, 8, 11, 14, 17, 20, 23],  # 0-based, depth=24
        upsample_mode='bilinear',     # bilinear / nearest
        single_dpi=240,
        summary_dpi=220,
        save_input=True,
        save_pca=True,
        save_meanact=True,
        save_overlay=True,
        save_attention=True,
        attention_head_fusion='mean',   # mean / max
        attention_task_token_indices=[0, 1, 2, 3, 4, 5, 6, 10, 14, 18, 22, 26, 30],  # 看哪些 task token
        save_attention_per_head=False,  # 是否把每个head单独保存
    )

    # dataset setting
    dataset_list = ['Human36M', 'MSCOCO', 'MPII', 'AGORA', 'EHF', 'UBody', 'HAA500', 'BEDLAM', 'InterHand26M', 'HInt']
    # trainset_3d = ['Human36M']; trainset_2d = ['MSCOCO', 'MPII']; testset = 'EHF'
    # trainset_3d = ['BEDLAM', 'InterHand26M', 'UBody']
    trainset_3d = ['InterHand26M', 'UBody', 'MSCOCO']
    trainset_3d_sample_prob = {'InterHand26M': 0.35, 'UBody': 0.25, 'MSCOCO': 0.40}
    trainset_2d = []; testset = 'EHF'  # Stage2 冻手训脸=UBody only；手部基线配方=['BEDLAM','InterHand26M']
    continue_train_path = "/workspace/myosx/output/dcnv4_hand_face/model_dump/snapshot_49.pth.tar"

    ## UBody setting
    train_sample_interval = 1
    test_sample_interval = 10 # original is 100, cause video to image is --fps 3
    make_same_len = False
    ubody_benchmark = False
    ubody_use_pkl_annotation = os.environ.get('UBODY_USE_PKL_ANNOTATION', '1').lower() not in ('0', 'false', 'no')
    # Empty = look for keypoint_annotation.pkl / smplx_annotation.pkl next to
    # their JSON files. Set UBODY_ANNOTATION_CACHE_DIR to keep caches outside
    # the dataset tree; layout is <cache_dir>/<scene>/*_annotation.pkl.
    ubody_annotation_cache_dir = os.environ.get('UBODY_ANNOTATION_CACHE_DIR', '')
    # Empty = use dataset/UBody/annotations. Set UBODY_ANNOTATION_DIR to a
    # pre-filtered annotation root generated by tool/UBody/filter_annotations_by_images.py.
    ubody_annotation_dir = os.environ.get('UBODY_ANNOTATION_DIR', '')

    ## HInt setting (test-only natural hand 2D benchmark)
    hint_root = os.environ.get('HINT_ROOT', '')
    hint_split = os.environ.get('HINT_SPLIT', 'test')
    # Comma separated subset filter matched against folder names, e.g.
    # "epick,newdays". Empty = all available split folders; partial HInt
    # Ego4D folders are skipped automatically when images are missing.
    hint_sources = os.environ.get('HINT_SOURCES', '')
    hint_sample_interval = int(os.environ.get('HINT_SAMPLE_INTERVAL', '1'))
    hint_max_samples = None
    hint_skip_missing_images = True
    hint_bbox_scale = 1.25

    ## BEDLAM setting
    bedlam_dir = os.environ.get('BEDLAM_DATASET_ROOT', '/workspace/BEDLAM_Dataset')
    bedlam_img_dir = os.environ.get('BEDLAM_IMG_DIR', bedlam_dir)
    bedlam_annot_path = os.environ.get('BEDLAM_PROCESSED_LABELS', osp.join(bedlam_dir, 'processed_labels'))
    bedlam_sample_interval = 2   # per-scene stride -> ~half (93k of 186k) while keeping all 29 scenes
    bedlam_max_samples = None    # no hard cap; sample_interval already halves uniformly
    bedlam_skip_missing_images = True
    bedlam_convert_flat_hand_mean = True
    # Dynamic hand-ROI quality gate (computed live in model_core from the
    # ACTUAL augmented box_net bbox; no offline file needed -> no flip/scale/rot
    # mismatch). The frozen top-down box_net can frame the wrong person on BEDLAM's
    # multi-person / occluded scenes, and UBody/MSCOCO full-body images can also
    # contain small or occluded hands, so a crop may miss the target hand joints. When
    # enabled for a source, if a predicted hand bbox covers < coverage_thr of
    # that hand's GT-valid joints, model_core masks ONLY that hand's hand-space
    # 2D losses (joint_proj / joint_img / smplx_joint_img); body / SMPL-X pose /
    # shape / joint_cam supervision is untouched. InterHand (GT bbox) is never
    # gated. The offline tool/BEDLAM/compute_hand_roi_quality.py is kept only for
    # the go/no-go decision and auditing, NOT loaded at train time.
    bedlam_use_hand_roi_quality = False
    ubody_use_hand_roi_quality = False
    mscoco_use_hand_roi_quality = False
    bedlam_hand_roi_coverage_thr = 0.6
    bedlam_hand_roi_min_joints = 8
    # Stage 3 calibration target. UBody hands are closer to target demo images
    # than BEDLAM, so do not assume BEDLAM's gate values are final; confirm with
    # short runs / gate diagnostics before locking the polish recipe.
    ubody_hand_roi_coverage_thr = 0.6
    ubody_hand_roi_min_joints = 8
    mscoco_hand_roi_coverage_thr = 0.6
    mscoco_hand_roi_min_joints = 8
    # B-class anti-pollution. The hand soft-argmax head (hand_position_net) takes
    # a feature-level ROI crop of img_feat (1024, 16, 12); on BEDLAM full-body
    # images a hand spans ~1 feature pixel, so its hand-local heatmap targets
    # (joint_img / smplx_joint_img) are an ill-posed signal. Those two losses are
    # the ONLY gradient source for the heatmap head (everywhere else hand_joint_img
    # is .detach()ed), and feeding BEDLAM into them collapses the shared head
    # mid-epoch (observed: joint_img 0.8 -> 3+ permanently, both sources, while
    # joint_proj / joint_cam / smplx_pose stay stable). When False, BEDLAM hand
    # joints are dropped from joint_img / smplx_joint_img only; BEDLAM hand
    # joint_proj and all SMPL-X / 3D / pose supervision are kept, and InterHand
    # hands are never affected. Default True = legacy behavior.
    bedlam_supervise_hand_img = True

    ## InterHand2.6M setting
    interhand_annot_path = os.environ.get('INTERHAND_ANNOS', '/workspace/OpenDataLab___InterHand2_dot_6M')
    interhand_img_dir = os.environ.get('INTERHAND_IMG_DIR', '/workspace/OpenDataLab___InterHand2_dot_6M/raw/InterHand2.6M_5fps_batch1/images')
    interhand_sample_interval = 1
    # Temporal de-duplication: InterHand frames are grouped by
    # (Capture, sequence, camera) = dirname(file_name). Within each group the
    # 5fps frames are near-identical, so keep only a few representative frames
    # spread evenly in time. This removes redundancy while preserving every
    # subject / gesture / camera view.
    interhand_dedup_by_group = True
    interhand_frames_per_group = 1
    interhand_max_samples = 80000
    interhand_skip_missing_images = True
    interhand_use_human_annot = True
    interhand_require_mano = True
    # Which InterHand annotation split the loader reads WHEN used as the eval
    # testset (file paths only; data_split stays "test" so augmentation is
    # identity). Default "test" = official benchmark. Set to "train" (via
    # test.py --interhand_eval_split) for an immediate, contaminated
    # upper-bound signal when the official test annotations aren't downloaded.
    interhand_eval_split = 'test'
    use_weighted_dataset_sampling = True

    use_hand_rotmat_pose_loss = False
    hand_rotmat_pose_loss_weight = 1.0
    phase1_epochs = 10
    phase1_train_hand_regressor = True
    train_face_modules = False
    # Stage gating, symmetric to train_face_modules. When False, the hand branch
    # (hand_position_net / hand_decoder / hand_regressor) is frozen like the
    # backbone (no grad, eval BN) and kept OUT of the optimizer, but its names
    # stay in trainable_module_names so the lightweight snapshot still carries
    # the (warm) hand weights — letting a later joint stage warm-start from it.
    # Used by the face-only stage: load _c's hands, freeze them, train only face.
    train_hand_modules = True
    # WA2D diagnostic/stabilization attempt: keep the warm-started hand_position_net
    # fixed while updating hand_decoder/hand_regressor. This isolates position-head
    # DCNv4 backward, but freeze runs can still hit non-finite gradients in the
    # decoder; it is not a stable recipe. The module name stays in
    # trainable_module_names so lightweight snapshots still carry its warm weights.
    freeze_hand_position_net = False
    # Body-shape T1 micro-experiment gate (default OFF). When True, the two
    # decoupled linear heads body_regressor.shape_out + cam_out are unfrozen
    # (body_regressor otherwise stays fully frozen) so betas/camera can be
    # finetuned on BEDLAM GT shape, independent of the hand/face line. When
    # False every related branch is a no-op (prefixes empty) — hand/face
    # training is byte-for-byte unchanged. See docs/experiment_log.md 2026-06-25.
    train_body_shape = False
    # Decoder isolation experiment (default OFF, hand only). When True the
    # train/test1 hand path swaps our HandDecoder for the OSX-style PoseurDecoder
    # (6-layer deformable-DETR with ITERATIVE reference-point refinement, which
    # HandDecoder lacks). Same (feats, coord_init, query_init)->features interface,
    # so the forward is unchanged; isolates whether iterative refinement helps.
    # OFF -> HandDecoder, byte-for-byte unchanged. Train and test1 MUST match.
    use_poseur_hand_decoder = False
    # Route C micro-experiment gate (default OFF). When True, hand_roi_net (the
    # feature-level hand crop+upsample, normally part of the frozen backbone) is
    # moved into the trainable set so it can co-adapt with the hand
    # decoder/regressor at a small lr (hand_roi_lr). Targets the UBody
    # full-body natural-hand gap: tests whether it is a predicted-box crop-
    # distribution mismatch (fixable here) vs. a frozen-feature ceiling (not).
    # box_net stays frozen on purpose. No-op when False -> byte-for-byte
    # unchanged. See docs/post_stage3_roadmap.md route C.
    train_hand_roi = False
    hand_roi_lr = 1e-6
    # End-tip 2D loss weighting (default 1.0 = OFF). Up-weight distal hand joints
    # (tip=_4, j3=_3) in the hand-space 2D losses (joint_proj/joint_img/
    # smplx_joint_img); targets the UBody natural-hand fingertip degradation
    # (tip/j3 are the worst per docs). 1.0/1.0 -> byte-for-byte unchanged.
    hand_tip_loss_weight = 1.0
    hand_j3_loss_weight = 1.0
    # Direct wrist-aligned natural-hand 2D loss (default OFF). Unlike the
    # existing hand-space losses, this is computed in full-body heatmap space
    # before hand-ROI coordinate rewriting: pred/GT are aligned by the wrist and
    # normalized by the GT hand-keypoint bbox diagonal, matching the UBody
    # natural-hand [wa] metric. Sources default to UBody+MSCOCO real hand 2D.
    hand_wa_2d_loss_weight = 0.0
    hand_wa_2d_loss_sources = 'ubody,mscoco'
    hand_wa_2d_loss_min_joints = 4
    hand_wa_2d_j1_weight = 1.0
    hand_wa_2d_j2_weight = 1.0
    hand_wa_2d_j3_weight = 1.0
    hand_wa_2d_tip_weight = 1.0
    # WA2D backward NaN guard (2026-06-30). err = dist / diag and diag is GT-only
    # (no grad), so the per-joint backward magnitude scales as 1/diag; the old
    # diag floor of 1e-4 let a tiny GT hand bbox push it to 1e4 (wrist 20x more),
    # which is finite but saturates the DCNv4 / hand_decoder deformable backward to
    # NaN (hand_tipw without this loss never NaN'd). diag is in output_hm_shape
    # units (full heatmap diagonal ~20); min_diag=1.0 bounds the per-finger grad at
    # <=1.0, comparable to the other 2D losses. err_clip hard-clamps the per-joint
    # normalized error so a single blown-up joint can't dominate (normal hands sit
    # at ~0.1-0.5, so 5.0 only touches garbage). Set min_diag=1e-4 + err_clip=0 to
    # reproduce the old NaN-prone behavior for ablation.
    hand_wa_2d_min_diag = 1.0
    hand_wa_2d_err_clip = 5.0
    # Skip-bad-batch guard (2026-06-30). The diag floor + err_clip above cut the
    # WA2D NaN blast radius ~20x but cannot fully prevent it: on a few natural-hand
    # batches the DCNv4 deformable-sampling BACKWARD kernel itself overflows (NaN is
    # born inside the sampling op — offset_mask/value_proj partial-NaN while
    # output_proj/norm2 stay finite), and WA2D only supplies the upstream gradient
    # magnitude. False (default) = strict: a non-finite grad aborts the run (old
    # behavior, byte-identical). True = detect non-finite grads after backward,
    # zero them, skip the optimizer step for that iter, and continue — one bad batch
    # in ~800 shouldn't kill a 4733-iter run. Skips are logged + counted.
    skip_nonfinite_grad = False
    # Optional warm-start (only consulted when continue_train is False): load the
    # trained hand/face tensors from a lightweight snapshot WITHOUT resuming the
    # epoch counter or optimizer state. Used to chain training stages
    # (e.g. face-only stage warm-starts hands from _c; joint stage warm-starts
    # both hands+face from the face-only stage).
    init_trained_path = ""
    # A-class stabilization for the soft-argmax hand_position_net, which is the
    # module observed to diverge mid-epoch (depth bins flip). It gets its own
    # optimizer group at lr * posnet_lr_mult and its own tighter grad clip, so
    # the rest of the hand/face modules keep the normal lr / global clip.
    posnet_lr_mult = 0.25
    posnet_grad_clip = 0.5
    # The frozen top-down box_net produces degenerate whole-frame hand boxes on
    # hand-centric datasets (e.g. InterHand). For samples flagged is_hand_only
    # with a valid GT hand bbox, feed the GT box into the hand ROI crop instead
    # of the box_net prediction. box_net predictions are still kept for the
    # (diagnostic) bbox loss, so this does not change what box_net learns.
    inject_gt_hand_bbox = True

    ## input, output size
    input_img_shape = (512, 384)
    input_body_shape = (256, 192)
    output_hm_shape = (16, 16, 12)
    input_hand_shape = (256, 256)
    output_hand_hm_shape = (16, 16, 16)
    output_face_hm_shape = (8, 8, 8)
    input_face_shape = (192, 192)
    focal = (5000, 5000)  # virtual focal lengths
    princpt = (input_body_shape[1] / 2, input_body_shape[0] / 2)  # virtual principal point position
    body_3d_size = 2
    hand_3d_size = 0.3
    face_3d_size = 0.3
    camera_3d_size = 2.5

    ## training config
    end_epoch = 14
    train_batch_size = 48
    # save one InterHand (pred boxes/crop) + one BEDLAM (mesh scatter) diagnostic
    # image per epoch under output/<exp>/vis/epoch_panel/
    vis_epoch_panel = True
    print_iters = 100
    lr_mult = 0.1
    smplx_loss_weight = 1
    agora_benchmark = False

    ## testing config
    test_batch_size = 16

    ## others
    num_thread = 16
    gpu_ids = '0'
    num_gpus = 1
    continue_train = False
    vis = False

    ## directory
    cur_dir = osp.dirname(os.path.abspath(__file__))
    root_dir = osp.join(cur_dir, '..')
    data_dir = osp.join(root_dir, 'dataset')

    output_dir, model_dir, vis_dir, log_dir, result_dir, code_dir = None, None, None, None, None, None
    human_model_path = osp.join(root_dir, 'common', 'utils', 'human_model_files')
    exp_name = 'output/exp1/pre_analysis'

    ## model setting
    pretrained_model_path = None
    upscale = 4
    encoder_pretrained_model_path = '../pretrained_models/osx_vit_l.pth'
    hand_pos_joint_num = 20
    face_pos_joint_num = 72
    encoder_setting = 'osx_l'
    decoder_setting = 'pytorch'
    num_task_token = 24
    feat_dim = 768
    num_noise_sample = 0
    encoder_config_file = os.path.join(root_dir, 'main/transformer_utils/configs/osx/encoder/body_encoder_large.py')

    def set_args(self, gpu_ids, lr=1e-4, continue_train=False):
        self.gpu_ids = gpu_ids
        self.num_gpus = len(self.gpu_ids.split(','))
        self.lr = float(lr)
        self.continue_train = continue_train
        os.environ["CUDA_VISIBLE_DEVICES"] = self.gpu_ids
        print('>>> Using GPU: {}'.format(self.gpu_ids))

    def set_additional_args(self, **kwargs):
        names = self.__dict__
        for k, v in kwargs.items():
            names[k] = v
        self.prepare_dirs(self.exp_name)
        if self.encoder_setting == 'osx_b':
            self.encoder_config_file = os.path.join(cfg.root_dir, 'main/transformer_utils/configs/osx/encoder/body_encoder_base.py')
            self.encoder_pretrained_model_path = '../pretrained_models/osx_vit_b.pth'
            self.feat_dim = 768
        elif self.encoder_setting == 'osx_l':
            self.encoder_config_file = os.path.join(cfg.root_dir, 'main/transformer_utils/configs/osx/encoder/body_encoder_large.py')
            self.encoder_pretrained_model_path = '../pretrained_models/osx_vit_l.pth'
            self.feat_dim = 1024
        if 'AGORA' in self.testset:
            self.testset = 'AGORA'
        if self.agora_benchmark:
            self.smplx_loss_weight = 2
            self.trainset_3d = ['AGORA']
            self.trainset_2d = []
            self.testset = 'AGORA'
        if self.ubody_benchmark:
            self.trainset_3d = ['Human36M'];
            self.trainset_2d = ['UBody', 'MSCOCO', 'MPII'];
            self.testset = 'UBody'
        if isinstance(self.hint_max_samples, str):
            self.hint_max_samples = int(self.hint_max_samples) if self.hint_max_samples else None

    def prepare_dirs(self, exp_name):
        self.output_dir = osp.join(self.root_dir, exp_name)
        self.model_dir = osp.join(self.output_dir, 'model_dump')
        self.vis_dir = osp.join(self.output_dir, 'vis')
        self.log_dir = osp.join(self.output_dir, 'log')
        self.code_dir = osp.join(self.output_dir, 'code')
        self.result_dir = osp.join(self.output_dir, 'result')
        make_folder(self.model_dir)
        make_folder(self.vis_dir)
        make_folder(self.log_dir)
        make_folder(self.code_dir)
        make_folder(self.result_dir)
        ## copy some code to log dir as a backup
        copy_files = ['main/config.py', 'main/train.py', 'main/test.py', 'common/base.py',
                      'main/OSX.py', 'main/model_core.py', 'common/nets', 'main/OSX_WoDecoder.py',
                      'data/dataset.py', 'data/MSCOCO/MSCOCO.py', 'data/AGORA/AGORA.py',
                      'data/BEDLAM/BEDLAM.py', 'data/InterHand26M/InterHand26M.py',
                      'data/HInt/HInt.py']
        for file in copy_files:
            os.system(f'cp -r {self.root_dir}/{file} {self.code_dir}')

cfg = Config()

## add some paths to the system root dir
sys.path.insert(0, cfg.root_dir)
# sys.path.insert(0, osp.join(cfg.root_dir, 'common'))
from common.utils.dir import add_pypath, make_folder
add_pypath(osp.join(cfg.data_dir))
for i in range(len(cfg.dataset_list)):
    add_pypath(osp.join(cfg.root_dir, 'data', cfg.dataset_list[i]))
add_pypath(osp.join(cfg.root_dir, 'data'))
add_pypath(cfg.data_dir)
