python test.py \
    --gpu 0 \
    --test_batch_size 32 \
    --decoder_setting pytorch \
    --testset InterHand26M \
    --interhand_eval_split test \
    --max_eval_iters -1 \
    --pretrained_model_path ../pretrained_models/osx_l.pth.tar \
    --exp_name output/eval_interhand_bedlam_c \
    --continue_train_paths ../output/interhand_bedlam_c/model_dump/snapshot_10.pth.tar  ../output/interhand_bedlam_c/model_dump/snapshot_8.pth.tar
# --continue_train_paths ../output/interhand_bedlam_c/model_dump/snapshot_*.pth.tar