#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

PYTHON_BIN="${PYTHON_BIN:-python}"
BEDLAM_DATASET_ROOT="${BEDLAM_DATASET_ROOT:-/workspace/BEDLAM_Dataset}"
BEDLAM_PROCESSED_LABELS="${BEDLAM_PROCESSED_LABELS:-${BEDLAM_DATASET_ROOT}/processed_labels}"
BEDLAM_FLAT_HAND_VERIFY_OUTPUT="${BEDLAM_FLAT_HAND_VERIFY_OUTPUT:-${BEDLAM_DATASET_ROOT}/flat_hand_verify}"
BEDLAM_FLAT_HAND_VERIFY_PATTERN="${BEDLAM_FLAT_HAND_VERIFY_PATTERN:-auto}"
BEDLAM_FLAT_HAND_VERIFY_SAMPLES="${BEDLAM_FLAT_HAND_VERIFY_SAMPLES:-4}"
BEDLAM_FLAT_HAND_VERIFY_TOL="${BEDLAM_FLAT_HAND_VERIFY_TOL:-1e-5}"
BEDLAM_JPG_QUALITY="${BEDLAM_JPG_QUALITY:-95}"

"${PYTHON_BIN}" "${PROJECT_ROOT}/tool/BEDLAM/verify_flat_hand_mean_conversion.py" \
  --project-root "${PROJECT_ROOT}" \
  --img-root "${BEDLAM_DATASET_ROOT}" \
  --label-dir "${BEDLAM_PROCESSED_LABELS}" \
  --output-dir "${BEDLAM_FLAT_HAND_VERIFY_OUTPUT}" \
  --pattern "${BEDLAM_FLAT_HAND_VERIFY_PATTERN}" \
  --num-samples "${BEDLAM_FLAT_HAND_VERIFY_SAMPLES}" \
  --tolerance "${BEDLAM_FLAT_HAND_VERIFY_TOL}" \
  --jpg-quality "${BEDLAM_JPG_QUALITY}" \
  "$@"
